### ISSUE TITLE
使用这个Forward框架进行推断的时候会有精度损失吗？

### ISSUE THREAD

**Issue by dgl547437235** [Tencent/Forward#10]

**Comment by yuanzexi** [comment]
@dgl547437235  FLOAT 推理模式下基本无损失；而 HALF 和 INT8 的推理模式下，因数据类型原因定会存在一定的精度损失。由于最终是以 TensorRT 的推理引擎进行推理，所以详细精度损失情况，可参考 TensorRT。

**Comment by Fan9** [comment]
NLP的Bert分类模型测试，`float 32` 精度没有损失。`Half`和`INT8`暂时还没测

**Comment by Fan9** [comment]
Bert的`float 16`也测过了，1000条样本的F1没有损失，可能也和具体任务有关

**Comment by yuanzexi** [comment]
@Fan9  感谢反馈！~
