### ISSUE TITLE
关于fwd-torch的几个路径的问题

### ISSUE THREAD

**Issue by dgl547437235** [Tencent/Forward#11]
![image](https://user-images.githubusercontent.com/31400928/116519895-99c94580-a904-11eb-8068-4e2c941ebebc.png)
你好,我在编译fwd-torch的时候，一直报找不到包的问题，如图，我想问这其中的CMAKE_PREFIX_PATH ，TORCH_DIR,TORCH_CMAKE_PATH都是关于torch的什么路径，是跟pytorch官方下的libtorch有关吗，具体是指定到其中的哪些路径

**Comment by dgl547437235** [comment]
![image](https://user-images.githubusercontent.com/31400928/116538294-ecf9c300-a919-11eb-9d75-248aca8975e3.png)
在部分情况下，可以cmake生成项目，但在编译阶段，出现了如上的错误，cmake选项如下图
![image](https://user-images.githubusercontent.com/31400928/116538422-14e92680-a91a-11eb-89ac-e1145ca74a24.png)

**Comment by yuanzexi** [comment]
@dgl547437235   
1. 关于第一个问题，CMAKE 的 message 有给提示，使用 libtorch 时，需要指定到 libtorch 目录下的 `share/cmake `，例如 `-DCMAKE_PREFIX_PATH=path\to\libtorch\share\cmake`
![image](https://user-images.githubusercontent.com/14813536/117431331-b2b4a500-af5b-11eb-820d-070f1b7b74ca.png)

2. 关于第二个问题：在 Windows 平台下，由于 PyTorch 自身 Python 版本库无法支持 Libtorch 编译，目前不支持 BUILD_PYTHON_LIB for Forward-Torch，所以需要关掉 BUILD_PYTHON_LIB，从而根据上述问题一的回答使用 CMAKE_PREFIX_PATH=/path/to/libtorch/share/cmake 来指定 libtorch 目录。

这里附上  cmake-gui 使用前的 add_entry。
![image](https://user-images.githubusercontent.com/14813536/117523512-5a2ce880-afeb-11eb-97e2-d943cad521ad.png)
