### ISSUE TITLE
vs2017怎么跑demo？

### ISSUE THREAD

**Issue by XuMicoder** [Tencent/Forward#15]
已经按照vs2017.bat内容cmake成功，下一步如何运行demo？求教

**Comment by yuanzexi** [comment]
@XuMicoder  可以直接打开 build 目录下的 Forward.sln 打开解决方案，然后点击 生成 -> 生成解决方案。

**Comment by XuMicoder** [comment]
![image](https://user-images.githubusercontent.com/80387578/119442693-e1ec5400-bd5a-11eb-91eb-1dc944db7842.png) 
 谢谢解答，但是生成解决方案的时候报了很多错误，错误计数超过100：正在停止编译  环境的话都是推荐环境，看了一下基本上都是plugin文件夹里的文件报错@yuanzexi

**Comment by yuanzexi** [comment]
@XuMicoder  看起来像是未正确配置 CUDA 相关环境变量，导致 Visual Studio 找不到 nvcc。你可以先试试找一个简单的 CUDA 程序来测试系统环境是否能正常跑 CUDA 程序。建议检查一下 CUDA 相关的环境变量，以及检查 CUDA 安装时是否有安装 Visual Studio Extensions.

**Comment by XuMicoder** [comment]
谢谢解答，我的环境变量暂时没啥问题，我检查过一切正常，新建cuda项目测试也没问题，cuda安装时将解压对应的文件我复制到了vs对应的目录里面去了，cmake的时候是可以找得到nvcc的，一开始我也以为是环境问题，然后我在另外一台设备上重新配置了环境全部按照推荐配置来，出现的问题是一样的。这个我暂时没能找到合理的解决办法，在Ubuntu上是正常的，win10上确实有出现些bug。@yuanzexi

**Comment by yuanzexi** [comment]
@XuMicoder  你可以提供一下，你的系统环境:
**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**:

**Comment by XuMicoder** [comment]
笔记本编译失败，配置如下：
TensorRT Version:7.2.1.6
NVIDIA GPU:NvidiaGTX2060
NVIDIA Driver Version: 27.21.14.6542
CUDA Version:10.2
CUDNN Version:8.0.4
Operating System:win10企业版Insider Preview
Python Version (if applicable):False
Tensorflow Version (if applicable):1.15.1
PyTorch Version (if applicable):False
vs版本：vs2017

同一台电脑对应的wsl2环境是：
TensorRT Version:7.2.1.6
NVIDIA GPU:NvidiaGTX2060
NVIDIA Driver Version: 27.21.14.6542
CUDA Version:10.2
CUDNN Version:8.0.2
Operating System:Ubuntu1804
Python Version (if applicable):False
Tensorflow Version (if applicable):1.15.1
PyTorch Version (if applicable):False
这台电脑是可以正常编译与test的

另外一台电脑的配置如下：
TensorRT Version:7.2.1.6
NVIDIA GPU:NvidiaGTX3080
CUDA Version:11.0
CUDNN Version:8.0.5
Operating System:win10专业版
Python Version (if applicable):False
Tensorflow Version (if applicable):1.15.1
PyTorch Version (if applicable):False
vs版本：vs2019
这台电脑系统是我重装的，与第一次一样的报错
