### ISSUE TITLE
编译出错 找不到cublas_device库

### ISSUE THREAD

**Issue by tianyu06030020** [Tencent/Forward#20]
你好， 编译的时候报cublas_device找不到，具体如下：

## Environment

**TensorRT Version**: 7.2.3.4
**CUDA Version**: 10.2
**CUDNN Version**: 7.4
**Operating System**: ubuntu18.04
**Python Version (if applicable)**: 3.7
**PyTorch Version (if applicable)**: 1.8

错误信息：
[ 97%] Linking CXX shared library ../../bin/libfwd_torch.so
[ 97%] Built target fwd_torch
Scanning dependencies of target forward
[ 98%] Building CXX object source/py_fwd/CMakeFiles/forward.dir/py_forward.cpp.o
[100%] Linking CXX shared module ../../bin/forward.cpython-37m-x86_64-linux-gnu.so
/usr/bin/x86_64-linux-gnu-ld: cannot find -****lCUDA_cublas_device_LIBRARY-NOTFOUND****
collect2: error: ld returned 1 exit status
source/py_fwd/CMakeFiles/forward.dir/build.make:117: recipe for target 'bin/forward.cpython-37m-x86_64-linux-gnu.so' failed
make[2]: *** [bin/forward.cpython-37m-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:687: recipe for target 'source/py_fwd/CMakeFiles/forward.dir/all' failed
make[1]: *** [source/py_fwd/CMakeFiles/forward.dir/all] Error 2
Makefile:83: recipe for target 'all' failed

cublas_device这个库找不到，cuda10以后这个库就废弃了吧。

**Comment by tianyu06030020** [comment]
> 你好， 编译的时候报cublas_device找不到，具体如下：
> ## Environment
> 
> **TensorRT Version**: 7.2.3.4
> **CUDA Version**: 10.2
> **CUDNN Version**: 7.4
> **Operating System**: ubuntu18.04
> **Python Version (if applicable)**: 3.7
> **PyTorch Version (if applicable)**: 1.8
> 
> 错误信息：
> [ 97%] Linking CXX shared library ../../bin/libfwd_torch.so
> [ 97%] Built target fwd_torch
> Scanning dependencies of target forward
> [ 98%] Building CXX object source/py_fwd/CMakeFiles/forward.dir/py_forward.cpp.o
> [100%] Linking CXX shared module ../../bin/forward.cpython-37m-x86_64-linux-gnu.so
> /usr/bin/x86_64-linux-gnu-ld: cannot find -****lCUDA_cublas_device_LIBRARY-NOTFOUND****
> collect2: error: ld returned 1 exit status
> source/py_fwd/CMakeFiles/forward.dir/build.make:117: recipe for target 'bin/forward.cpython-37m-x86_64-linux-gnu.so' failed
> make[2]: *** [bin/forward.cpython-37m-x86_64-linux-gnu.so] Error 1
> CMakeFiles/Makefile2:687: recipe for target 'source/py_fwd/CMakeFiles/forward.dir/all' failed
> make[1]: *** [source/py_fwd/CMakeFiles/forward.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> 
> cublas_device这个库找不到，cuda10以后这个库就废弃了吧。


这个问题我解决了，是cmake版本比较低，升级一下就可以了。

**Comment by tianyu06030020** [comment]
> > 你好， 编译的时候报cublas_device找不到，具体如下：
> > ## Environment
> > **TensorRT Version**: 7.2.3.4
> > **CUDA Version**: 10.2
> > **CUDNN Version**: 7.4
> > **Operating System**: ubuntu18.04
> > **Python Version (if applicable)**: 3.7
> > **PyTorch Version (if applicable)**: 1.8
> > 错误信息：
> > [ 97%] Linking CXX shared library ../../bin/libfwd_torch.so
> > [ 97%] Built target fwd_torch
> > Scanning dependencies of target forward
> > [ 98%] Building CXX object source/py_fwd/CMakeFiles/forward.dir/py_forward.cpp.o
> > [100%] Linking CXX shared module ../../bin/forward.cpython-37m-x86_64-linux-gnu.so
> > /usr/bin/x86_64-linux-gnu-ld: cannot find -****lCUDA_cublas_device_LIBRARY-NOTFOUND****
> > collect2: error: ld returned 1 exit status
> > source/py_fwd/CMakeFiles/forward.dir/build.make:117: recipe for target 'bin/forward.cpython-37m-x86_64-linux-gnu.so' failed
> > make[2]: *** [bin/forward.cpython-37m-x86_64-linux-gnu.so] Error 1
> > CMakeFiles/Makefile2:687: recipe for target 'source/py_fwd/CMakeFiles/forward.dir/all' failed
> > make[1]: *** [source/py_fwd/CMakeFiles/forward.dir/all] Error 2
> > Makefile:83: recipe for target 'all' failed
> > cublas_device这个库找不到，cuda10以后这个库就废弃了吧。
> 
> 这个问题我解决了，是cmake版本比较低，升级一下就可以了。

最后生成了python库，但是我导入的时候，报错了：
ImportError: forward.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN5torch3jit8toIValueEN8pybind116handleERKSt10shared_ptrIN3c104TypeEENS4_8optionalIiEE

**Comment by yuanzexi** [comment]
你的 CMAKE 命令是怎样的呢？以及 CMake 的 Output 信息方便提供一下吗？

**Comment by tianyu06030020** [comment]
> 你的 CMAKE 命令是怎样的呢？以及 CMake 的 Output 信息方便提供一下吗？

谢谢回复，这个我也解决了，pytorch版本的问题。但是我模型转换engine的时候遇到问题了：

2021-06-17 10:12:21,342 INFO  [default] TrtActivationDesc::CreateLayer
2021-06-17 10:12:21,342 INFO  [default] TrtOutputDesc::CreateLayer
2021-06-17 10:12:21,342 INFO  [default] maxWorkSpaceSize = 1073741824
2021-06-17 10:12:27,247 INFO  [default] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
2021-06-17 10:12:40,996 FATAL [default] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
../rtSafe/cublas/cublasLtWrapper.cpp:279
Aborting...
2021-06-17 10:12:40,997 WARN  [default] Aborting application. Reason: Fatal log at [project/Forward/source/trt_engine/trt_common/trt_logger.cpp:58]
Aborted (core dumped)

这个看不出哪里出错了

**Comment by tianyu06030020** [comment]
> > 你的 CMAKE 命令是怎样的呢？以及 CMake 的 Output 信息方便提供一下吗？
> 
> 谢谢回复，这个我也解决了，pytorch版本的问题。但是我模型转换engine的时候遇到问题了：
> 
> 2021-06-17 10:12:21,342 INFO [default] TrtActivationDesc::CreateLayer
> 2021-06-17 10:12:21,342 INFO [default] TrtOutputDesc::CreateLayer
> 2021-06-17 10:12:21,342 INFO [default] maxWorkSpaceSize = 1073741824
> 2021-06-17 10:12:27,247 INFO [default] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
> 2021-06-17 10:12:40,996 FATAL [default] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
> ../rtSafe/cublas/cublasLtWrapper.cpp:279
> Aborting...
> 2021-06-17 10:12:40,997 WARN [default] Aborting application. Reason: Fatal log at [project/Forward/source/trt_engine/trt_common/trt_logger.cpp:58]
> Aborted (core dumped)
> 
> 这个看不出哪里出错了

btw: 我转换的模型就是pix2pix_hd模型！！

**Comment by yuanzexi** [comment]
@tianyu06030020   这个应该是 CUDA 10.2 的 CUBLAS 需要打两个补丁。 https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal  
直接下载的 CUDA 10.2.89 版本在对 CublasLt 的支持上有问题。需要打补丁支持。
![image](https://user-images.githubusercontent.com/14813536/122378927-f9ed7700-cf98-11eb-9ea8-4f2658c0cda8.png)

**Comment by tianyu06030020** [comment]
> @tianyu06030020 这个应该是 CUDA 10.2 的 CUBLAS 需要打两个补丁。 https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal
> 直接下载的 CUDA 10.2.89 版本在对 CublasLt 的支持上有问题。需要打补丁支持。
> ![image](https://user-images.githubusercontent.com/14813536/122378927-f9ed7700-cf98-11eb-9ea8-4f2658c0cda8.png)

@yuanzexi 非常感谢，装了补丁之后可以转成功了，但是加速不太明显，v100上大概只有10%左右的提升。请问，你们对GAN网络有测试过加速性能吗。

**Comment by yuanzexi** [comment]
> > @tianyu06030020 这个应该是 CUDA 10.2 的 CUBLAS 需要打两个补丁。 https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal
> > 直接下载的 CUDA 10.2.89 版本在对 CublasLt 的支持上有问题。需要打补丁支持。
> > ![image](https://user-images.githubusercontent.com/14813536/122378927-f9ed7700-cf98-11eb-9ea8-4f2658c0cda8.png)
> 
> @yuanzexi 非常感谢，装了补丁之后可以转成功了，但是加速不太明显，v100上大概只有10%左右的提升。请问，你们对GAN网络有测试过加速性能吗。

@tianyu06030020   FP32 模式加速可能只有 10 %左右，你可以试试看 FP16 和 int8 的加速。应该会加速明显一些。
