### ISSUE TITLE
是否考虑重新写一个模型序列化？？

### ISSUE THREAD

**Issue by chenjun2hao** [Tencent/Forward#26]
我看项目中采用`TrtNetworkDesc`来进行模型转换，那是否考虑将`TrtNetworkDesc`保存下来，这样做到模型转换和推理分离。可以在不同trt版本上用同样的`TrtNetworkDesc`。

**Comment by zhaoyiluo** [comment]
Hi @chenjun2hao ，

Forward 项目的初衷是模型推理加速，即 模型导入 -(Phase 1)- 生成引擎 -(Phase 2)- 完成推理。你所提及的 `TrtNetworkDesc`，它是 Phase 1 的一个中间产物，并不涉及需要将它保存到本地文件。

如果需要在不同的 trt 版本上使用同样的 `TrtNetworkDesc`，你只需额外实例化几个不同的 <Platform>Builder，通过调用 Build 就可以得到目标引擎。
