### ISSUE TITLE
Transformer for neural machine translation

### ISSUE THREAD

**Issue by yjegssl** [Tencent/Forward#3]
Is forward supporting transformer for neural machine translation?

**Comment by yuanzexi** [comment]
So far, Forward only support BERT model.

**Comment by xieydd** [comment]
@yjegssl  For Transformer model, maybe you can see this project in tencent https://github.com/Tencent/TurboTransformers

**Comment by yuanzexi** [comment]
Yes, this project (https://github.com/Tencent/TurboTransformers) could help.
