### ISSUE TITLE
make报错

### ISSUE THREAD

**Issue by Nipi64310** [Tencent/Forward#33]
**Describe the bug**
执行命令：
`cmake .. -DTensorRT_ROOT=/home/soft/wp/TensorRT-8.2.0.6 -DENABLE_TORC                                                                H=ON -DENABLE_TORCH_PLUGIN=ON -DCMAKE_PREFIX_PATH=/home/soft/wp/libtorch`

错误日志：
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "11.1")
-- CUDA_NVCC_FLAGS:  -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75
-- Using the single-header code from /home/soft/wp/Forward/source/third_party/json/single_include/
-- Found TensorRT: /home/soft/wp/TensorRT-8.2.0.6/lib/libnvinfer.so;/home/soft/wp/TensorRT-8.2.0.6/lib/libnvinfer_plugin.so;/home/soft/wp/TensorRT-8.2.0.6/lib/libnvonnxparser.so;/home/soft/wp/TensorRT-8.2.0.6/lib/libnvparsers.so (found version "8.2.0")
-- Found CUDA: /usr/local/cuda (found version "11.1")
-- Caffe2: CUDA detected: 11.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 11.1
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so
-- Found cuDNN: v?  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
CMake Error at /home/soft/wp/libtorch/share/cmake/Caffe2/public/cuda.cmake:174 (message):
  PyTorch requires cuDNN 7 and above.
Call Stack (most recent call first):
  /home/soft/wp/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/soft/wp/libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:248 (find_package)

-- Configuring incomplete, errors occurred!

实际上是已经安装了cudnn
![image](https://user-images.githubusercontent.com/31469418/138238960-036ecd8b-c3a9-40e6-a854-df4ffd1b60f0.png)

ls /usr/local/cuda/lib64 | grep cudnn
![image](https://user-images.githubusercontent.com/31469418/138239261-95ad7245-f311-4257-9cc7-2ab0b1e74f0f.png)

## Environment

**TensorRT Version**: TensorRT-8.2.0.6
**NVIDIA GPU**: P8
**NVIDIA Driver Version**: 465.19.01
**CUDA Version**:  11.1
**CUDNN Version**:  8.2.1.32
**Operating System**: Ubuntu 16.04.2 LTS 
**Python Version (if applicable)**: 3.7
**Tensorflow Version (if applicable)**: 2.6.0
**PyTorch Version (if applicable)**: 1.9.0+cu111

## Relevant Files

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zhaoyiluo** [comment]
Hello @Nipi64310 ，Forward 已适配 TensorRT 8 [Release v2.0.0](https://github.com/Tencent/Forward/releases/tag/v2.0.0)，同时也向前兼容了 TensorRT 7；后续我们也会在 transformer 方向进一步做优化，请耐心等待，也欢迎提 issues 哈 :)

**Comment by ZiyueWu59** [comment]
> cmake成功了

您好，想请问一下具体是如何操作使得cmake成功了呢
