### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by evil-potato** [Tencent/Forward#4]
**Describe the bug**
When I finished compiling cmake，then I copy **forward.cpython-36m-aarch64-linux-gnu.so** to a new directory, I run '**python test_forward.py**'  or ‘**import forward**’，an error appear '  **Segmentation fault (core dumped)**  '

## Environment

Device :   Jetson Xavier NX 
System:    Jetpack4.4 [L4T 32.4.4]
**TensorRT Version**:   7.1.3
**CUDA Version**:    10.2.89
**CUDNN Version**:   8.0.0.180
**Python Version (if applicable)**:    3.6.9
**Tensorflow Version (if applicable)**:  1.15.2
**Keras Version (if applicable)**:    2.1.5

## Relevant Files
cmake successful
![4](https://user-images.githubusercontent.com/56706604/112803829-4ade8500-90a6-11eb-89c4-b273c49c25b9.png)

error information
![3](https://user-images.githubusercontent.com/56706604/112803881-5a5dce00-90a6-11eb-8fdf-11d609c00cba.png)

some gdb information 
![1](https://user-images.githubusercontent.com/56706604/112803916-60ec4580-90a6-11eb-91ad-2b92a151fafa.png)
![2](https://user-images.githubusercontent.com/56706604/112804082-8da05d00-90a6-11eb-989d-730f08c22cfc.png)

What causes such error?
Looking forward to the answer！！

**Comment by yuanzexi** [comment]
@evil-potato  Could you please specify your GCC version, ld version?

**Comment by evil-potato** [comment]
> @evil-potato Could you please specify your GCC version, ld version and your HDF 5 version?
GCC version :    **gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)** 
ld version : **GNU ld (GNU Binutils for Ubuntu) 2.30**
HDF 5 version:
![image](https://user-images.githubusercontent.com/56706604/112927373-75cce580-9147-11eb-9085-2d4f3c9b7a52.png)

**Comment by yuanzexi** [comment]
Would you mind provide a screenshot of your Cmake log infos? like this.
![image](https://user-images.githubusercontent.com/14813536/112940934-6a39e880-9160-11eb-8810-361c270e75d1.png)

**Comment by evil-potato** [comment]
> Would you mind provide a screenshot of your Cmake log infos? like this.
> ![image](https://user-images.githubusercontent.com/14813536/112940934-6a39e880-9160-11eb-8810-361c270e75d1.png)

Do you mean this file？
This is the cmakeoutput.log ，I wonder if it will help you
[CMakeOutput.log](https://github.com/Tencent/Forward/files/6226592/CMakeOutput.log)

**Comment by yuanzexi** [comment]
We cannot reproduce this bug. Considering pre-installed HDF5 packages have many compatible problems, we plan to include HDF5 source codes as third-party in our project later.

**Comment by yuanzexi** [comment]
We add HDF5 sources as the third project on recently commits. You could pull them and try again. The problem might be caused by `_GLIBCXX_USE_CXX11_ABI=0` setting in the original https://github.com/Tencent/Forward/blob/master/CMakeLists.txt. So far, this setting is dropped for Keras.

**Comment by evil-potato** [comment]
> We add HDF5 sources as the third project on recently commits. You could pull them and try again. The problem might be caused by `_GLIBCXX_USE_CXX11_ABI=0` setting in the original https://github.com/Tencent/Forward/blob/master/CMakeLists.txt. So far, this setting is dropped for Keras.

When I run **test_ forward.py** .An error appears as follows

![image](https://user-images.githubusercontent.com/56706604/114126741-96f1bb00-992b-11eb-8e33-806d0912009b.png)

**Log**
![image](https://user-images.githubusercontent.com/56706604/114126602-56923d00-992b-11eb-9c98-386fb431ce00.png)

**Comment by yuanzexi** [comment]
@evil-potato  It seems that some ops are not supported yet. If possible, you could provide the model for us to support.
