### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by BoBoer** [Tencent/Forward#5]
**Describe the bug**
An error is reported at the end of the program, free(): invalid pointer.

## Environment

**TensorRT Version**: 7.2.3.4
**NVIDIA GPU**: TITAN Xp
**NVIDIA Driver Version**: 440.33.01
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.4
**Operating System**: CentOS 8
**Python Version (if applicable)**: 3.6.8
**Tensorflow Version (if applicable)**: --
**PyTorch Version (if applicable)**: 1.3.1 (libtorch cpu)

## Relevant Files

**To Reproduce**
Build Forward:
cmake -DENABLE_LOGGING=OFF \
-DENABLE_PROFILING=OFF \
-DENABLE_DYNAMIC_BATCH=OFF \
-DENABLE_TORCH=ON \
-DBUILD_PYTHON_LIB=OFF \
-DPYTHON_EXECUTABLE=/usr/bin/python3 \
-DENABLE_TENSORFLOW=OFF -DENABLE_KERAS=OFF \
-DTORCH_CMAKE_PATH=/usr/local/lib/libtorch/share/cmake/Torch/ \
..
1. #include "fwd_torch/torch_engine/torch_engine.h"
#include "fwd_torch/torch_engine/torch_infer.h"
2. create main function
 std::cout << "Hello World" << std::endl;
after cmake and make, run this function.

**Expected behavior**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/35909828/112801424-73b14b00-90a3-11eb-963b-c2e3cd8c8e5c.png)

**Additional context**
The problem occurs in Forward cmake with libtorch.
When we use Forward which cmake with python, the problem do not come up.

**Comment by yuanzexi** [comment]
@BoBoer  You could try to use -DCMAKE_PREFIX_PATH=/usr/local/lib/libtorch  instead of -DTORCH_CMAKE_PATH. And you'd better not to  include `"fwd_torch/torch_engine/torch_infer.h"`, which is used internally. You could follow https://github.com/Tencent/Forward/tree/master/demo/fwd_cpp to use Fwd-Cpp

**Comment by BoBoer** [comment]
It has been done according to the above instructions, but the problem still exists.

**Comment by yuanzexi** [comment]
Which libtorch did you use? Could you provide the link address of your libtorch libraries?

**Comment by BoBoer** [comment]
https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.3.1%2Bcpu.zip

**Comment by yuanzexi** [comment]
Did you clean the CMakeCache.txt in the `build` directory? If you build with `-DBUILD_PYTHON_LIB=ON` first, and then you build with `-DBUILD_PYTHON_LIB=OFF`. In this case, if you didn't clean CMakeCache.txt, the cmake project would use the python-torch libraries instead of the libtorch you specified. This may result in some conflicts.

**Comment by BoBoer** [comment]
I have clean the CMakeCache.txt. I run `rm -rf * ` in the build directory before cmake.

**Comment by yuanzexi** [comment]
Could you please provide your GCC version and ld version?
