### ISSUE TITLE
[TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input

### ISSUE THREAD

**Issue by mydear33000** [Tencent/Forward#9]
dl frame: tensorflow 1.15
model: mobilenet_v2_1.4_224_frozen.pb
input name: input
input size: 1,224,224,3
-----------------------------------------------------
error info: 
[INFO ] 2021-04-08 14:38:59,844 tf_graph_parser.cpp(116): Input = input : input
[INFO ] 2021-04-08 14:38:59,844 tf_shuffle_creator.h(50): TrtShuffleDesc::Create
[INFO ] 2021-04-08 14:38:59,844 tf_softmax_creator.h(49): TrtSoftmaxDesc::Create
[INFO ] 2021-04-08 14:38:59,844 tf_shuffle_creator.h(50): TrtShuffleDesc::Create
[INFO ] 2021-04-08 14:38:59,845 tf_shuffle_creator.h(50): TrtShuffleDesc::Create
[INFO ] 2021-04-08 14:38:59,845 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,916 tf_pooling_creator.h(51): TrtPoolingDesc::Create
[INFO ] 2021-04-08 14:38:59,916 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,916 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,929 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,941 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,941 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:38:59,941 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:38:59,941 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,941 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,941 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,946 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:38:59,947 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,954 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,954 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:38:59,954 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:38:59,954 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,954 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,954 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,960 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:38:59,961 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,966 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,966 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:38:59,966 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:38:59,966 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,967 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,967 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,973 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,977 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,977 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:38:59,977 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:38:59,977 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,977 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,977 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,979 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:38:59,980 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,982 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,982 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:38:59,982 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:38:59,982 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,982 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,982 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,984 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:38:59,985 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,988 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,988 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:38:59,988 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:38:59,988 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,989 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,989 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,991 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,992 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,992 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:38:59,992 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:38:59,992 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,992 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,992 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,993 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:38:59,994 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,995 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,995 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:38:59,995 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:38:59,995 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,995 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,995 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,996 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:38:59,997 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,998 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,998 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:38:59,998 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:38:59,998 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,998 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:38:59,998 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:38:59,999 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:38:59,999 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,000 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,000 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:39:00,001 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:39:00,001 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,001 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,001 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,002 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,002 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,002 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:39:00,002 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:39:00,002 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,003 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,003 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,004 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:39:00,004 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,004 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,004 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:39:00,004 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:39:00,004 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,004 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,004 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,005 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:39:00,005 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,005 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,005 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:39:00,005 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:39:00,005 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,005 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,005 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,005 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:39:00,006 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_element_wise_creator.h(54): TrtElementWiseDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:39:00,006 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:39:00,006 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:39:00,007 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,007 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,007 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,007 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,007 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,007 tf_batch_norm_creator.h(51): TrtNormalizationDesc::Create
[INFO ] 2021-04-08 14:39:00,007 tf_batch_norm_creator.h(78): BatchNorm Use Scale Implementation
[INFO ] 2021-04-08 14:39:00,007 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,007 tf_clamp_creator.h(50): TrtClampDesc::Create
[INFO ] 2021-04-08 14:39:00,007 tf_convolution_creator.h(72): TrtConvolutionDesc::Create
[INFO ] 2021-04-08 14:39:00,588 trt_input_creator.h(44): TrtInputDesc::CreateLayer
[INFO ] 2021-04-08 14:39:00,588 trt_convolution_creator.h(44): TrtConvolutionNdDesc::CreateLayer
[INFO ] 2021-04-08 14:39:00,589 trt_clamp_creator.h(44): TrtClampDesc::CreateLayer
[ERROR] 2021-04-08 14:39:00,589 trt_logger.cpp(64): [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input.
[ERROR] 2021-04-08 14:39:00,589 trt_logger.cpp(64): [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input.
[INFO ] 2021-04-08 14:39:00,589 trt_convolution_creator.h(44): TrtConvolutionNdDesc::CreateLayer
[INFO ] 2021-04-08 14:39:00,589 trt_scale_creator.h(43): TrtScaleDesc::CreateLayer
[INFO ] 2021-04-08 14:39:00,589 trt_clamp_creator.h(44): TrtClampDesc::CreateLayer
[ERROR] 2021-04-08 14:39:00,589 trt_logger.cpp(64): [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input.
[ERROR] 2021-04-08 14:39:00,589 trt_logger.cpp(64): [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input.
[INFO ] 2021-04-08 14:39:00,589 trt_convolution_creator.h(44): TrtConvolutionNdDesc::CreateLayer
[INFO ] 2021-04-08 14:39:00,589 trt_convolution_creator.h(44): TrtConvolutionNdDesc::CreateLayer
[INFO ] 2021-04-08 14:39:00,589 trt_clamp_creator.h(44): TrtClampDesc::CreateLayer
[ERROR] 2021-04-08 14:39:00,589 trt_logger.cpp(64): [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input.
[ERROR] 2021-04-08 14:39:00,589 trt_logger.cpp(64): [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input.
[INFO ] 2021-04-08 14:39:00,589 trt_convolution_creator.h(44): TrtConvolutionNdDesc::CreateLayer
[INFO ] 2021-04-08 14:39:00,589 trt_scale_creator.h(43): TrtScaleDesc::CreateLayer
[INFO ] 2021-04-08 14:39:00,589 trt_clamp_creator.h(44): TrtClampDesc::CreateLayer
[ERROR] 2021-04-08 14:39:00,589 trt_logger.cpp(64): [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input.
[ERROR] 2021-04-08 14:39:00,589 trt_logger.cpp(64): [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input.

**Comment by yuanzexi** [comment]
Would you mind provide the environment, the pb model or the frozen script you used? If possible, you can follow steps on the below template:


**Describe the bug**
A clear and concise description of what the bug is.


## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 

## Relevant Files



**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
